Hexbindec
cawacawa/SelfEdu pull request #2
Opened 2020-11-13 13:06 UTC by cawacawa

2020-11-13 13:14 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +// ���, �? ������ ���� ��?
В сорцах (исходных кодах) не должно быть комментариев на языке отличном от англа

2020-11-13 13:18 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +	else return -1;
В общем все норм, но я бы наверное переписал немного этот if иначе.
"Если нулевой элемент ноль, то сделать внутри true блока 2 проверки на b и на х.
В блоке false проверить, если  >= '0' и <= '9'. И в конце концов,если никда не попали, то return -1"

2020-11-13 13:18 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +int INDEX_IN(char* str)
почему стиль именования функций разный? эта почему-то вся капсом

2020-11-13 13:18 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +	const int size = 100;
Нужно переписать функцию. Она должна уметь работать со строками любой длинны.

2020-11-13 13:20 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +int strToInt(const char* str,const int size,int index)
придерживайся одно стиля. В заголовке этой функции у тебя нету пробелов между параметрами , а в ф-ции выше есть.

2020-11-13 13:22 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +void inStr(char* str, int size)
Если я прав, то эта фукнция нигде не юзается - мусор, удаляй.

2020-11-13 14:57 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +		res[i++] = digits[num % index];
прикольное решение 👍

2020-11-13 14:57 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +	cout << endl;
В общем-то на сейчас ок, но в идеале ты должен возвращать буфер с готовой строкой (типа "0x1232") , а не выводить сразу в консоль. Для этого придется переделать немного

2020-11-14 13:25 UTC, cawacawa commented on hexbindec.main.cpp
> +// ���, �? ������ ���� ��?
Готово

2020-11-14 13:25 UTC, cawacawa commented on hexbindec.main.cpp
> +	else return -1;
Готово

2020-11-14 13:25 UTC, cawacawa commented on hexbindec.main.cpp
> +int INDEX_IN(char* str)
Готово

2020-11-14 13:25 UTC, cawacawa commented on hexbindec.main.cpp
> +int strToInt(const char* str,const int size,int index)
Готово

2020-11-14 13:25 UTC, cawacawa commented on hexbindec.main.cpp
> +void inStr(char* str, int size)
Готово

2020-11-14 15:47 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +	else return -1;
а это поч не удалил?

2020-11-14 15:49 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +	else if (str[1] >= '0' && str[1] <= '9') return 10;
а что будет если я введу `*024`
?)

2020-11-14 16:26 UTC, ZaharBozhok commented on hexbindec.main.cpp
> +int my_strlen(char* str,int index)
index не используется

2020-11-14 20:15 UTC, ZaharBozhok requested changes

2020-11-14 20:15 UTC, ZaharBozhok commented on numbersconvertor1/main.cpp
> +	}
дублирование кода, подумай как от него избавиться

2020-11-14 20:15 UTC, ZaharBozhok commented on numbersconvertor1/main.cpp
> +	}
По идее это уже не надо

2020-11-26 10:36 UTC, ZaharBozhok approved these changes

2020-11-26 10:36 UTC, merged